version: "3.8"

services:
  casdoor:
    build:
      context: ./
      dockerfile: Dockerfile
      target: STANDARD
    image: casdoor-custom:latest
    container_name: casdoor
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "8002:8000"
    environment:
      - RUNNING_IN_DOCKER=true
    volumes:
      - ./conf:/conf
      - ./data:/data
    restart: unless-stopped
    networks:
      - haina-net

networks:
  haina-net:
    external: true
